### ISSUE TITLE
Install fails on Windows following the instructions as written

### ISSUE THREAD

**Issue by johnmbarrett** [LINCellularNeuroscience/VAME#1]
Creating a conda environment, installing pytorch, then running setup.py fails on Windows. Seems to be an issue with installing scipy and can be solved by specifying scipy<=1.2.1 when creating the conda environment (not sure how critical the exact version is, I pulled it from the setup.py). Mostly putting this here in case anyone else runs into the same problem.

Steps to reproduce:-

1) Open Command Prompt in the vame repo folder
2) `conda create -n vametest`
3) `conda activate vametest`
4) Install pytorch for your system, e.g. in my case `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`
5) `python setup.py install`

Expected behaviour: VAME installed.

Actual behaviour: [a huge error message](https://github.com/LINCellularNeuroscience/VAME/files/4639319/vame.install.error.log.txt), attached. Main problem seems to be the following:

```
Running scipy-1.2.1\setup.py -q bdist_egg --dist-dir C:\Users\LSPS2\AppData\Local\Temp\easy_install-xjjkkxxc\scipy-1.2.1\egg-dist-tmp-ckxdo8qj
C:\Users\LSPS2\AppData\Local\Temp\easy_install-xjjkkxxc\scipy-1.2.1\setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\LSPS2\AppData\Local\Temp\easy_install-xjjkkxxc\scipy-1.2.1\setup.py:377: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command, proceeding with "
Running from scipy source directory.
Could not locate executable g77
Could not locate executable f77
Could not locate executable ifort
Could not locate executable ifl
Could not locate executable f90
Could not locate executable DF
Could not locate executable efl
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable g95
Could not locate executable efort
Could not locate executable efc
Could not locate executable flang
don't know how to compile Fortran code on platform 'nt'
```
Additional notes: as mentioned up top, can be fixed by changing step 2 to `conda create -n vametest scipy<=1.2.1`.

System info:-

Windows 10 x64
Conda 4.8.3
Python 3.7.7
CUDA 10.1.105

**Comment by KLuxem** [comment]
Thank you for bringing this up. We work on it to resolve it asap.

**Comment by pavolbauer** [comment]
Hi John,
Thanks for trying out Vame!
It seems there is a bug with the scipy version 1.2.1 and numpy 1.18, particularly appearing in a python 3.8 environment. We work on finding a solution for this, meanwhile we recommend to install Vame in a python 3.7 environment. (create -n vame_env python=3.7) or using your fix.
Cheers
Pavol

**Comment by KLuxem** [comment]
We tested VAME now without specifying scipy<=1.2.1 under Windows, Ubuntu and Mac OS. 
The new setup.py is updated and I hope this will work smoothly for everyone. 
Best,
Kevin
