### ISSUE TITLE
Egocentric Data: Negative Values are an issue?

### ISSUE THREAD

**Issue by JensBlack** [LINCellularNeuroscience/VAME#10]
Me again,

I created an egocentric representation of my mouse with the mouse spanned on the y-Axis between Neck and Tailroot (set new origin and rotated the coordinates). I also normalized the mouse for good measure based on its length to create a somewhat norm mouse representation. This created a dataframe with values around -2 to 2 around the origin 0,0.
When trying to create a trainingset (with vame.create_trainset(config)), I was got an error in line 39 in `vame/model/create_training.py`:

```
    seq_inter = np.zeros((X.shape[0],X.shape[1]))
    for s in range(num_features):
        seq_temp = X[s,:]
        seq_pd = pd.Series(seq_temp)
        if np.isnan(seq_pd[0]):
            -->seq_pd[0] = next(x for x in seq_pd if not np.isnan(x))
        seq_pd_inter = seq_pd.interpolate(method="linear", order=None)
        seq_inter[s,:] = seq_pd_inter
```
The error simple stated "Stop Iteration"

As this directly followed after issue #9 , I tried to pinpoint the issue and investigated my input '.npy' again.
Truncating the data to 10 rows did not solve the issue, but I was able to convince myself that the data itself is clean. No NaN's, empty entries, weird dtypes. Nothing.
Only that i had negative values.
So I just added +100 to all values... and it worked.

The model is happily training for now. Can you elaborate?

**Comment by KLuxem** [comment]
Hi Jens,

I tried to reproduce your error and with negative values centered around 0 as well as high negative values it worked out fine for me. I also started out with NaN values to see if this causes the error but everything worked fine. 

Could you run your data with a debugger (e.g. pdb) and see which data value caused the exception?

Best,
Kevin

**Comment by JensBlack** [comment]
Hi Kevin,

 i will try out and report back to you!

**Comment by JensBlack** [comment]
closing the issue, because it probably an issue from my side. I will report back once I found it!
