### ISSUE TITLE
Error in pose segmentation

### ISSUE THREAD

**Issue by tue132** [LINCellularNeuroscience/VAME#101]
Hi all,

Thank you for developing fancy tool.

I am trying to build the VAME on the computing cluster of my institute and google colab. But, following errors occured and reproduced in both environment during pose segmentation process. I am using example files and training model was successfully converged.

Am I lack some value to add the config file? Do you know how to fix this? Thanks.

colab:
```
Pose segmentation for VAME model: VAME 

Using CUDA
GPU active: True
GPU used: Tesla T4
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-e14c13c35e2d> in <module>
----> 1 vame.pose_segmentation(config)

/content/drive/MyDrive/Colab Notebooks/vame/VAME/vame/analysis/pose_segmentation.py in pose_segmentation(config)
    248             torch.device("cpu")
    249 
--> 250         if not os.path.exists(os.path.join(cfg['project_path'],"results",file,model_name, parameterization+'-'+str(n_cluster),"")):
    251             new = True
    252              print("Hello1")

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

my environments:
```
Pose segmentation for VAME model: VAME 

Using CUDA
GPU active: True
GPU used: Tesla K80
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-e14c13c35e2d> in <module>
----> 1 vame.pose_segmentation(config)

~/VAME/vame/analysis/pose_segmentation.py in pose_segmentation(config)
    248             torch.device("cpu")
    249 
--> 250         if not os.path.exists(os.path.join(cfg['project_path'],"results",file,model_name, parameterization+'-'+str(n_cluster),"")):
    251             new = True
    252             # print("Hello1")

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by tue132** [comment]
That works! Thank you.

**Comment by kailiwu0707** [comment]
Hello! I encountered the same problem and set 'parameterization: hmm'.
However, when I ran vame.motif_videos soon after, it showed 'file not found error'. It seems k-means is the default. Do you know how to deal with this problem? Thanks in advance!

Here is the error code and my file folder: 
![image](https://user-images.githubusercontent.com/123570765/214601450-a7513cb3-fc13-4d37-89a1-c6638b42a26b.png)
![image](https://user-images.githubusercontent.com/123570765/214601668-5754d1d7-7db1-4832-97c6-03388811bc70.png)
