### ISSUE TITLE
VAME to multiple videos across conditions.

### ISSUE THREAD

**Issue by Wulin-Tan** [LINCellularNeuroscience/VAME#103]
Hi, VAME developers
How can we apply VAME to multiple videos across conditions? say, 3 animals in test group VS 3 animals in control group.
can I just concatenate the 6 csv files into a single csv and then run VAME ?
And thanks a lot for answering the question about multiple animals. 
Wulin

**Comment by pavolbauer** [comment]
Hi Wulin,

VAME uses the same parametrization of videos by default, so if you add the videos and then train and predict, it will be by default possible to compare the motif distributions / utilization.
Is that clear? For some more info also have a look at our practical workflow guide in the published version of the paper: https://www.nature.com/articles/s42003-022-04080-7

Best
Pavol

**Comment by Wulin-Tan** [comment]
@pavolbauer Hi, 
yes, that really helps!
And I think all I need to do is to list all the videos, including both test and control group,  into the following command: 

_config = vame.init_new_project(project='Your-VAME-Project', videos=['/directory/to/your/video-1','/directory/to/your/video-2','...'], working_directory='/YOUR/WORKING/DIRECTORY/', videotype='.mp4')_

we can run the workflow and finally in the result folder, video-1/video-2...subfolders would contain the results for each video. Then we can compare this results across conditions.

Is that right? pls correct me if anything is missing in my understanding. 
thank you.

Wulin
