### ISSUE TITLE
Evaluate model error: "AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'"

### ISSUE THREAD

**Issue by weberisla** [LINCellularNeuroscience/VAME#106]
<img width="1155" alt="Screen Shot 2023-02-14 at 1 30 29 AM" src="https://user-images.githubusercontent.com/56141523/218695088-0d5230a0-d881-4517-beb6-5ec86dfa505b.png">

Running up against this error when trying to evaluate my model in Google Colab. I'm not sure what the issue is here, would appreciate pointers.

Possibly unrelated, but my current version of torch is 1.13.1, whereas I think I saw somewhere that 1.5.0 may be required?

**Comment by pavolbauer** [comment]
Hi there,

exactly, that method calls a function that is related to the PyTorch Dataloader and imported via torch.utils.data. Please try upgrading to PyTorch 1.5, we developed VAME with that version.

Best,
Pavol

**Comment by weberisla** [comment]
Hi Pavol, 

Thanks for confirming this! I've upgraded PyTorch but now am having issues with model training, possibly due to the errors listed after upgrading? Let me know if you have a suggestion here, and apologies if there is an easy fix I am unaware of!

<img width="1383" alt="Screen Shot 2023-02-23 at 1 55 29 PM" src="https://user-images.githubusercontent.com/56141523/221039401-7a1e4eb5-4663-4765-976a-4ddd0de08f19.png">

<img width="1405" alt="Screen Shot 2023-02-23 at 1 55 39 PM" src="https://user-images.githubusercontent.com/56141523/221039381-0734ae08-4134-464e-a0d3-054962a715fa.png">

**Comment by G-Hepburn** [comment]
I ran into a similar issue with PyTorch today. I tried to downgrade to PyTorch 1.5 but google colab is not letting me downgrade to anything lower than PyTorch 1.7.1.

**Comment by pavolbauer** [comment]
Thanks for letting us know, we will evaluate if VAME works with the newest PyTorch version.

**Comment by G-Hepburn** [comment]
> Thanks for letting us know, we will evaluate if VAME works with the newest PyTorch version.

I managed to get the evaluation to work with PyTorch 2.0 by editing the evaluate.py file. In line 32, I changed it from: 

x = test_loader.__iter__().next()

to 

x = test_loader.__iter__().__next__()

Then, it worked. So, hopefully that can resolve it for anyone else with the same issue.

**Comment by pshonma** [comment]
We encountered the same error and had a similar solution to @G-Hepburn but changed Line 32 of evaluate.py to:

x = next(test_loader.__iter__())

This seems to have fixed the issue as well.

**Comment by pavolbauer** [comment]
Happy to announce that this fix is now included in the new commits in the master branch.
BR
Pavol
