### ISSUE TITLE
Colab training issue

### ISSUE THREAD

**Issue by jelrod14** [LINCellularNeuroscience/VAME#108]
This is similar to issue [46](https://github.com/LINCellularNeuroscience/VAME/issues/46) but I am not sure how they corrected this. I am using the example file and video, and have placed them into a folder called VAME_Example in my drive. I initialize the project and move the csv into the pose folder, but the video doesn't get moved into the project videos folder despite having the correct path to the video. 
`videos = '/content/drive/MyDrive/VAME_Example/video-1.mp4'`

This is causing (I think?) the create training dataset to fail:
`Creating training dataset...
Using robust setting to eliminate outliers! IQR factor: 4
Creating trainset from the vame.csv_to_numpy() output 

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-38-0b963ac88fd0>](https://localhost:8080/#) in <module>
----> 1 vame.create_trainset(config)

1 frames

[/content/VAME/vame/model/create_training.py](https://localhost:8080/#) in traindata_fixed(cfg, files, testfraction, num_features, savgol_filter, check_parameter)
    237         X_train.append(X_z)
    238 
--> 239     X = np.concatenate(X_train, axis=0).T
    240 
    241     if savgol_filter:

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate`

Not sure why it is trying to call the csv to numpy, because I did not use this as I egocentrically aligned the data

Thanks in advance!

**Comment by xiaoli26** [comment]
came into the same problem

**Comment by jelrod14** [comment]
Managed to figure it out, for some reason my project was initializing wrong and not copying video correctly. After restarting from scratch essentially and renaming all project variables it started working and copying video. 


I am now running into a new problem, however, where only some of my videos are being copied into the video folder upon project initialization. I am not sure if this is a google drive issue or a VAME issue. I have about 200 videos and it is only copying the first 58


Thanks in advance for the help.

**Comment by pavolbauer** [comment]
Hey,

Sounds like a google drive issue, we tested Vame project initialization with a couple of hundred videos already.

Best
Pavol
