### ISSUE TITLE
csv_to_numpy() got an unexpected keyword argument 'datapath'

### ISSUE THREAD

**Issue by xiaoli26** [LINCellularNeuroscience/VAME#110]
vame.csv_to_numpy(config, datapath='\\PATH\\TO\\YOUR\\.CSV')
error: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-71-2dfdadb39ea1>](https://localhost:8080/#) in <module>
----> 1 vame.csv_to_numpy(config,datapath='C:\\Research\\VAME\\vame_alpha_release-Mar16-2021\\videos\\pose_estimation\\')

TypeError: csv_to_numpy() got an unexpected keyword argument 'datapath'

**Comment by pavolbauer** [comment]
If you see the function definition (https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/util/csv_to_npy.py) you will find that csv to numpy takes only one argument,  and that's the (path to the) config.

**Comment by xiaoli26** [comment]
> If you see the function definition (https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/util/csv_to_npy.py) you will find that csv to numpy takes only one argument, and that's the (path to the) config.

Thank you for your guidance!

**Comment by xiaoli26** [comment]
I'm afraid some expression in the workflow guide might mislead the bachelor like me such as "vame.csv_to_numpy(config, datapath='\\PATH\\TO\\YOUR\\.CSV')"

**Comment by pavolbauer** [comment]
Thanks for spotting that, it will be corrected
