### ISSUE TITLE
Issue about storing the latent vector of videos.(segment_behavior.py)

### ISSUE THREAD

**Issue by giles-hu** [LINCellularNeuroscience/VAME#12]
In the file "segment_behavior.py"
`def cluster_latent_space(cfg, files, z_data, **z_logger**, cluster_method, n_cluster, model_name):`
In this function, there is a input called **z_logger** but **z_logger** is not used within the function at all. Besides, there is a variable **idx** is also not used within the for loop inside the function called  cluster_latent_space.  

When I have a group of videos,  I've noticed that the length of **labels for each videos** have the **exactly same size** which is equal to the number of **labels of the whole video library**. Therefore, it might cause mislabeling when generating corresponding videos like the function called "get_cluster_vid". Also, the function of z_logger is to log the segmentation of z_data, but it is not stored in result.  

Besides, I would suggest to store both the z_data for the whole video library and z_data for each video.

Personally, I edit your code a bit to avoid those minor problems:
```
def cluster_latent_space(cfg, files, z_data, z_logger, cluster_method, n_cluster, model_name):    
    for cluster in n_cluster:
        if cluster_method == 'kmeans':
            print('Behavior segmentation via k-Means for %d cluster.' %cluster)
            data_labels = kmeans_clustering(z_data, n_clusters=cluster)
            data_labels = np.int64(scipy.signal.medfilt(data_labels, cfg['median_filter']))
            
        if cluster_method == 'GMM':
            print('Behavior segmentation via GMM.')
            data_labels = gmm_clustering(z_data, n_components=cluster)
            data_labels = np.int64(scipy.signal.medfilt(data_labels, cfg['median_filter']))
            
        #save latent vector
        print("Saving latent vector..." )
        if not os.path.exists(cfg['project_path']+'results_latent'):
                os.mkdir(cfg['project_path']+'results_latent')
        
        np.save(cfg['project_path']+'results_latent'+os.sep+str(cluster)+'_zdata', z_data)
        np.save(cfg['project_path']+'results_latent'+os.sep+str(cluster)+'_zlogger', z_logger)
        if cluster_method == 'kmeans':
            np.save(cfg['project_path']+'results_latent'+os.sep+str(cluster)+'_km_label', data_labels)
        
        for idx, file in enumerate(files):
            print("Segmentation for file %s..." %file )
            if not os.path.exists(cfg['project_path']+'results/'+file+'/'+model_name+'/'+cluster_method+'-'+str(cluster)):
                os.mkdir(cfg['project_path']+'results/'+file+'/'+model_name+'/'+cluster_method+'-'+str(cluster))
        
            save_data = cfg['project_path']+'results/'+file+'/'+model_name+'/'
            labels = data_labels[z_logger[idx]:z_logger[idx+1]-1]
            latent_v = z_data[z_logger[idx]:z_logger[idx+1]-1]

                
            if cluster_method == 'kmeans':
                np.save(save_data+cluster_method+'-'+str(cluster)+'/'+str(cluster)+'_km_label_'+file, labels)
                
            if cluster_method == 'GMM':
                np.save(save_data+cluster_method+'-'+str(cluster)+'/'+str(cluster)+'_gmm_label_'+file, labels)
            
            if cluster_method == 'all':
                np.save(save_data+cluster_method+'-'+str(cluster)+'/'+str(cluster)+'_km_label_'+file, labels)
                np.save(save_data+cluster_method+'-'+str(cluster)+'/'+str(cluster)+'_gmm_label_'+file, labels)
                
            # store z data
            np.save(save_data+cluster_method+'-'+str(cluster)+'/'+str(cluster)+'_latent_vector_'+file, latent_v)
```

I am a beginner at GitHub. This is the first time for posting issues. So I have no idea about how to report something like this.  Please forgive me if I have posted Please forgive me if I have posted anything inappropriate. If you think it is better to contact you with email, please let me know. 

Many thanks in advance.

**Comment by KLuxem** [comment]
Thank you for bringing up this issue. 
I checked the script and you are right, it is currently storing the labels for all videos instead of each individual video. Your fix is absolutely fine and I also fixed the script now.  

With that I think we can close this issue.

Best, 
Kevin
