### ISSUE TITLE
Dimension of latent space

### ISSUE THREAD

**Issue by ask5898** [LINCellularNeuroscience/VAME#128]
This is more of a conceptual question. Generally VAEs are used to compress data into a lower dimensional latent space. However, in VAME, the input is of size Num_framesx12 and the latent dimension is (Num_frames-time_window)x30, which is a higher dimension. This is a bit counter-intuitive to the use of a VAE. Could you please clarify this?
thanks

**Comment by pavolbauer** [comment]
Hi,
The input size *for one time step* is time_window x number_of_dlc_markers, given a window of 30 and 12 markers that would be 360, for example.

On the contrary, the latent space *for one time step* is as defined - default is 30 but can be as little as 10 in some cases (for simple patterns).

So the compression rate would be 360/30 = 12 for the default case ( and could he much higher).

Hope this helps
Best
Pavol

**Comment by ask5898** [comment]
Oh yes that helps. Thanks for the clarification!!!
