### ISSUE TITLE
Reconstruction and Prediction Improvements

### ISSUE THREAD

**Issue by DongHur** [LINCellularNeuroscience/VAME#14]
Hello! Thank you for sharing this amazing program. I just had a quick question about how I can improve on my reconstruction and prediction. This is what I have so far:
**data_size = 300k**
<img width="272" alt="Screen Shot 2020-07-01 at 12 40 55 AM" src="https://user-images.githubusercontent.com/21997355/86207155-8bb76680-bb33-11ea-981a-df810e8a63f1.png">
![MSE-and-KL-LossVAME](https://user-images.githubusercontent.com/21997355/86207169-9114b100-bb33-11ea-9347-f96e72710226.png)
![Future_Reconstruction1](https://user-images.githubusercontent.com/21997355/86207195-9e31a000-bb33-11ea-8d01-72b7e7d4fa7c.png)
![Future_Reconstruction4](https://user-images.githubusercontent.com/21997355/86207219-a558ae00-bb33-11ea-9fca-253c47ea3492.png)
![Future_Reconstruction7](https://user-images.githubusercontent.com/21997355/86207238-b2759d00-bb33-11ea-855c-482e51dadda1.png)

I think the reconstruction does relatively well, but do you think I can do better? I am currently thinking of increasing zdims and time_window to pick up more granularity and reconstruct longer movements better. The prediction on the other hand is not too good in my opinion.

I also applied UMAP to getting these embedding. (Note, I set the n_cluster=30 for right now, but I think I will change this later)
![ant](https://user-images.githubusercontent.com/21997355/86207533-60814700-bb34-11ea-9955-a02f818f7d67.png)
![ant_scatter](https://user-images.githubusercontent.com/21997355/86207534-61b27400-bb34-11ea-9263-82f3ca89eec6.png)

**Comment by KLuxem** [comment]
Hi,

thank you for using VAME! In general, your reconstruction as well as the training loss look quite good. Increasing the latent dimension would might cause the model to not learn important features of your data. You could, however, increase the hidden layer size of your encoder RNN, e.g. to 512 if you have enough GPU power. Of course playing with your time_window size is also an option you can explore. Note that the prediction will always be a little more uncertain than the reconstruction as it serves rather as an additional regularization term for the reconstruction learning. Alternatively, you also have the option to only learn using the reconstruction decoder if you set prediction_decoder=0. 

In general, the lower the dimension of your latent space (zdims), the more important features the model needs to find in your data to embed and reconstruct. The reconstruction might get not as precise, however it might learn a better representation in the latent space. A good validation is to look at your motif videos and see if the behavior looks consistent within a motif.

Cheers,
Kevin
