### ISSUE TITLE
Interaction with objects?

### ISSUE THREAD

**Issue by blogeman** [LINCellularNeuroscience/VAME#17]
This looks like a great piece of software and something I would love to dig into. For my application I have a single animal that I am interested in, which interacts with multiple tracked points. My DLC pose estimates are the single animal of interest and objects of interest that the mouse interacts with. Is it possible to use the location of these objects with VAME?

**Comment by pavolbauer** [comment]
Hi Brandon,
Thanks for your interest in VAME, this sounds like an interesting task.
If I understand you right you are interested in the relationship between the animal body pose and the position of some objects that the mouse is exploring.
You could definitely experiment with including information on this relationship into VAME.
To capture this relationship I would suggest generating new time series that could capture these dependencies, e.g. the distance between the object and some virtual marker coordinate of the animal (e.g. the snout).
Likewise, one could think of the heading-direction angle in relationship to the object.
You could try to embed this information together with the egocentrically aligned pose estimates and see if clustering gives you some meaningful motifs showing specific movement patterns with dependence on the object.
Best regards
Pavol
