### ISSUE TITLE
motif_video error 

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [LINCellularNeuroscience/VAME#19]
Hi, 

Thank you for the great tool!

Sorry to bring this up again, I'm experiencing the same problem as in Issue #11. 
Unfortunately I can't go around the error message: `'UnboundLocalError: local variable 'fps' referenced before assignment'`

Do I have to implement the workaroung for .avi files in videowriter.py from VAME\vame\analysis or VAME\build\lib\vame, or the VAME\dist .egg file?

Best,
Guillermo

**Comment by KLuxem** [comment]
Hi Guillermo,

thank you for using VAME! 

We are currently working on our next release which also includes fixing this bug. 

As a workaround, you simply can change the `capture = cv.VideoCapture(cfg['project_path']+'videos/'+file+'.mp4')` command in line 23 in this [script ](https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/analysis/videowriter.py). It should work for you if you replace `.mp4` with `.avi`. 

I hope this will solve your problem. 

Best,
Kevin

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Dear Kevin, 

sorry for the delay, the workaround worked perfectly. 
I was forgetting to run `python setup.py install` again after the changes... ups 

Great project btw, thank you!
