### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by johnmbarrett** [LINCellularNeuroscience/VAME#2]
There seem to be some dependencies not listed in the setup.py, specifically pytest, pyyaml, and opencv-python, that cause install to fail when following the installation instructions.

Steps to reproduce:-

1) Open a command prompt in the VAME repo folder
2) `conda create -n vametest2 scipy<=1.2.1` (see [issue #1](https://github.com/LINCellularNeuroscience/VAME/issues/1) for why specifying scipy is necessary)
3) `conda activate vametest2`
4) Install pytorch, e.g. `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`
5) `python setupy.py install`---fails with error "The 'pytest' distribution was not found and is required by pytest-shutil"
6) `conda install pytest`
7) Repeat step 5
8) Open python, type `import vame`---fails with "ModuleNotFoundError: No module named 'yaml'"
9) Quit python, enter `conda install pyyaml`
10) Repeat step 8---fails with "ModuleNotFoundError: No module named 'cv2'"
11) Quit python, enter `conda install opencv-python`
12) Repeat step 8.

Expected behaviour: running setup.py installs VAME successfully the first time (i.e. step 5) and then VAME can be imported in Python

Actual behaviour: there are a few missing dependencies, namely pytest, pyyaml, and opencv-python, that have to be installed before running setup.py so that VAME can be used.

Also, there's a typo on line 44 of vame/model/create_training.py: should be `test = int(num_frames*cfg['test-fraction'])` (not `TestFraction`).

System info:-

Windows 10 x64
Conda 4.8.3
Python 3.7.7
CUDA 10.1.105

**Comment by KLuxem** [comment]
Thank you again! We will also look into this issue and find a solution.

**Comment by pavolbauer** [comment]
Hi John,
Thanks trying out VAME!
It seems there is a bug with the scipy version 1.2.1 and numpy 1.18, particularly appearing in a python 3.8 environment. We work on finding a solution for this, meanwhile we recommend to install Vame in a python 3.7 environment. (`create -n vame_env python=3.7`).
Cheers
Pavol

**Comment by pavolbauer** [comment]
Thanks John, we have added the dependencies into setup.py, the installation works with python 3.7.

**Comment by johnmbarrett** [comment]
Works on my system too! Thanks for the quick fix and thanks in general for the cool paper and toolbox!
