### ISSUE TITLE
Plotting and further analysis

### ISSUE THREAD

**Issue by KonradDanielewski** [LINCellularNeuroscience/VAME#21]
Hi,

not really an issue but rather a question. It's my first time using an autoencoder and I'm still learning python. Could you point me in the right direction, where to start with my analysis. I finished the workflow and looked at the numpy arrays in results but I'm not sure what to do with them and what are they.

If anyone could help me, even by giving me some link to a tutorial on analysing this kind of data or what to use to plot a video like the one in readme with motif and change in cluster I'd be super grateful!

Thank you,
Konrad

**Comment by alexcwsmith** [comment]
Hi Konrad,
I haven't worked out how to plot the video as is shown in the readme, but if you want to compare motif usage across groups of animals, you can check out my fork of this repository (https://github.com/alexcwsmith/VAME), where I have uploaded my workflow, with some functions (in vame/custom/helperFunctions.py) to extract motif usage from the numpy arrays for each animal and do groupwise comparisons.

Hope this helps. Soon I will try to tackle OpenCV to create the videos with motif labels as is in the readme...
Alex

**Comment by KonradDanielewski** [comment]
Hi Alex,

thanks for the reply! I'll try it out today - hope I can reach out if I'll have any problems or questions?

Thanks again,
Konrad

**Comment by alexcwsmith** [comment]
Sure thing Konrad, feel free to reach out either on the forked repo or you can email me directly at alexander.smith@mssm.edu.

**Comment by pavolbauer** [comment]
Thanks for providing your analysis workflow, @alexcwsmith , that is very usefull!
@KonradDanielewski we are in the process of updating our codebase with the analysis scripts providing, for example, the hierarchical analysis results from the paper along with some worked examples, which will be provided soon.
However, a good start for your analysis can be the plotting of group usage statistics as shown in Alex' scripts.
