### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'path/train_seq.npy'

### ISSUE THREAD

**Issue by tburnett108** [LINCellularNeuroscience/VAME#25]
Hello,

I'm attempting VAME for the first-time, and I encountered the above error, and train_seq.npy doesn't exist anywhere in the path. Is there anything I can do?

**Comment by pavolbauer** [comment]
Hi,
Could you post a traceback of your error, showing in which line the error started? Furthermore the settings in your config.yaml would be relevant to find the cause of the error.
Best,
Pavol

**Comment by tburnett108** [comment]
Hi Pavol,

I'd be happy to, could you post a link to the message you're referring to?
I'm having trouble finding it. I've posted previously about issues with
creating videos/frames and calculating the distance. Is this the problem
you're referring to?

Cheers,
-Thomas

**Comment by pavolbauer** [comment]
Hi Thomas,

I am referring to the full traceback of the error that occured in python.
Fo further explanations see [this link](https://realpython.com/python-traceback/).
The config.yaml is the config file for your project, see the explanation [here](https://github.com/LINCellularNeuroscience/VAME/wiki/1.-VAME-Workflow).

Best,
Pavol

**Comment by tburnett108** [comment]
Apologies! I realized I hadn't initialized the project correctly and was in the wrong directory. My mistake

**Comment by pavolbauer** [comment]
No worries.
