### ISSUE TITLE
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by kangel429** [LINCellularNeuroscience/VAME#29]
1) Is it correct to execute align_demo.py in order to display the output like the picture on the web page?

<img width="650" alt="1" src="https://user-images.githubusercontent.com/4396377/108624079-d6506f00-7485-11eb-8f0a-a5f8051fff74.png">

2) When align_demo.py is executed, the following error occurs. How can I fix this error?

C:\Users\kangel\AppData\Local\Continuum\anaconda3\envs\vame\python.exe D:/Project/AI/Dog/VAME-master/examples/align_demo.py
Traceback (most recent call last):
  File "D:/Project/AI/Dog/VAME-master/examples/align_demo.py", line 300, in <module>
    egocentric_time_series = align_demo(path_to_file, filename, file_format, crop_size, use_video=False, check_video=False)
  File "D:/Project/AI/Dog/VAME-master/examples/align_demo.py", line 284, in align_demo
    pose_flip_ref, bg, frame_count, use_video)
  File "D:/Project/AI/Dog/VAME-master/examples/align_demo.py", line 152, in align_mouse
    i = interpol(i)
  File "D:/Project/AI/Dog/VAME-master/examples/align_demo.py", line 83, in interpol
    nans, x = nan_helper(y[0])
  File "D:/Project/AI/Dog/VAME-master/examples/align_demo.py", line 75, in nan_helper
    return np.isnan(y), lambda z: z.nonzero()[0]
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Process finished with exit code 1

Please help me :(

**Comment by KLuxem** [comment]
Hi,

so far we haven't published the code to get the gif on our github mainpage. The script you are mentioning is for the egocentrical alignment of the csv file output from deeplabcut. 

If you are interested in this code, I could send you a version of it via E-Mail. 

Cheers,
Kevin

**Comment by kangel429** [comment]
Please send me a version of it. my E-Mail is kangel429@nate.com

Thank you so much :)
