### ISSUE TITLE
Structure of latent_vector.npy 

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [LINCellularNeuroscience/VAME#32]
Hi, and thank you for the nice toolbox! 

I am trying to work with the outputs, i.e., separating data by motifs, running umaps etc, and I was wondering about the structure of the latent_vector numpy file. 
The latent_vector output seems to have twice the size of the input_data_PE-seq-clean.npy (twice the num_features). Is it save to assume the first half corresponds to the reconstruction and the second to the prediction?

Best Regards, 
Guillermo

**Comment by KLuxem** [comment]
Hi Guillermo!

Thank you for working with VAME! We just released our new stable version and I think it would be worth it for you to go ahead and install this one. We had a few bugs within the segmentation function and now everything is much smoother organized. 

But regarding your question, the latent vector should be the same size as the frame size of your input video (minus 30 frames as we take away 15 frames in the beginning and 15 in the end with a time window size of 30). The latent vector itself is the resulting embedding vector with every data point in it and is not split up between reconstruction or prediction as it is learned through the encoding and decoding/prediction step. I hope this clears things up for you.

Cheers,
Kevin

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Uups, I really got that wrong, thanks for clarifying!
Looking forward to test your new release :)
