### ISSUE TITLE
RuntimeError: svd_cuda: For batch 0: U(129,129) is zero, singular U.

### ISSUE THREAD

**Issue by MMathisLab** [LINCellularNeuroscience/VAME#37]
Hey @KLuxem, testing out the new rnn_vae.py code I am hitting an issue with the `cluster_loss`. (Note, I also tried to set a project up with the demo video-1.py but I actually couldn't make a training set.) However, I can confirm the data I am using I could use this past weekend before the big change. 

torch.__version__ is `1.8.0+cu101`

Here is the traceback (source of error is here): https://github.com/LINCellularNeuroscience/VAME/blob/705a709be36b8b5ad1d02532e59f2b34343c970e/vame/model/rnn_vae.py#L47

```python
A VAME project has been created. 

Next use vame.create_trainset(config) to split your data into a train and test set. 
Afterwards you can use vame.rnn_model() to train the model on your data.

conversion from DeepLabCut csv to numpy complete...
DATA CONVERTED, CREATING TRAINING SET...

Creating training dataset...
Lenght of train data: 159570
Lenght of test data: 17730
batches size set to: 128
max epochs set to: 50
num_features set to: 22

TRAINING VAME MODEL...
Train Variational Autoencoder - Model name: VAME 

Using CUDA
GPU active: True
GPU used:  Tesla P100-PCIE-16GB
Latent Dimensions: 30, Time window: 30, Beta: 1, lr: 0.0005

Compute mean and std for temporal dataset.
Initialize train data. Datapoints 159570
Initialize test data. Datapoints 17730
Scheduler step size: 100, Scheduler gamma: 0.20

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/vame/model/rnn_vae.py", line 48, in cluster_loss
    _ ,sv_2, _ = torch.svd(gram_matrix)
RuntimeError: svd_cuda: For batch 0: U(129,129) is zero, singular U.
```

**Comment by MMathisLab** [comment]
I also tested a try / except for the svd based on some advice from here: https://github.com/pytorch/pytorch/issues/28293 without luck.

```python
def cluster_loss(H, kloss, lmbda, batch_size):
    gram_matrix = (H.T @ H) / batch_size
    try:
        _ ,sv_2, _ = torch.svd(gram_matrix)
    except:                     # torch.svd may have convergence issues for GPU and CPU.
        _ ,sv_2, _ = torch.svd(gram_matrix + 1e-4*gram_matrix.mean()*torch.rand(20, 20))

    #_ ,sv_2, _ = torch.svd(gram_matrix)
    sv = torch.sqrt(sv_2[:kloss])
    loss = torch.sum(sv)
    return lmbda*loss
```


```python
Traceback (most recent call last):
  File "testscript.py", line 58, in <module>
    vame.train_model(config)
  File "/usr/local/lib/python3.7/dist-packages/vame/model/rnn_vae.py", line 339, in train_model
    TRAIN_BATCH_SIZE, noise)
  File "/usr/local/lib/python3.7/dist-packages/vame/model/rnn_vae.py", line 133, in train
    kmeans_loss = cluster_loss(latent.T, kloss, klmbda, bsize)
  File "/usr/local/lib/python3.7/dist-packages/vame/model/rnn_vae.py", line 50, in cluster_loss
    _ ,sv_2, _ = torch.svd(gram_matrix + 1e-4*gram_matrix.mean()*torch.rand(20, 20))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by KLuxem** [comment]
Hi Mackenzie,

hmm thats puzzling as I did not do any changes to the `cluster_loss` function and also no big changes to the model itself. 
So far I also never encountered this particular error `RuntimeError: svd_cuda: For batch 0: U(129,129) is zero, singular U.`

I will think about it and try to find a solution. Might be a pytorch related bug?

**Comment by MMathisLab** [comment]
I tried rolling back to just `1.8.0` (as checked on march 14th), same issue :( -- maybe there is some issue with batch_size now from config. (I should sleep on it :) thanks @KLuxem !

**Comment by KLuxem** [comment]
I will run some tests tomorrow to see if I can find a reason for this behavior as well. I am sure we will figure it out :)

**Comment by KLuxem** [comment]
Short update: I tried different batch sizes and see no errors coming up. The only difference I see so far is that I am running with `torch version 1.7.1 `

**Comment by alexcwsmith** [comment]
Any update on this? I am not getting the exact same error as you Mackenzie, but I am getting weird CUDA errors in the middle of training (have yet to be able to run a training to convergence on the update), and it seems like training is using wayyy more CPU power than it should, and a pretty small amount of GPU. This is the only thing I use PyTorch rather than TensorFlow for so not sure if PyTorch inherently passes things from CPU to GPU more, or if there is something wrong with my configuration / versions etc?

**Comment by alexcwsmith** [comment]
Ok after I rolled back to Torch 1.7.1 I did get a model to train through to convergence without any CUDA/CPU errors, still odd to me that this uses so much CPU during training though...

**Comment by kvnlxm** [comment]
I will close this issue for now. By now, we also don't use the kmeans VAE objective anymore. You can easily apply this by setting  `kmeans_lambda: 0 `in your _config.yaml_. 

Cheers,
Kevin
