### ISSUE TITLE
Installation VAME 1.0

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [LINCellularNeuroscience/VAME#38]
Hi All, 

thank you again for this tool, super exciting!

Problem:
I was having troubles installing the new VAME release with the VAME.yaml and setup.py with some pip errors poping up, something like `AttributeError: module 'brotli' has no attribute 'error'`.

Solution:
After manually installing all dependencies in the VAME.yaml in the new environment running `python setup.py install`  worked again. 

Best,
Guillermo

**Comment by KLuxem** [comment]
Hi Guillermo,

thank you for your kind words and for reporting this bug. So far we have not encountered this but I leave this Issue open to see if others have similar problems.

Cheers,
Kevin

**Comment by KLuxem** [comment]
Closing the issue.

Cheers, Kevin
