### ISSUE TITLE
What is the pose file?

### ISSUE THREAD

**Issue by bramn22** [LINCellularNeuroscience/VAME#4]
Hi,

After creating a new project, it is mentioned that I have to add my pose file into the /videos/pose-estimation folder. What is this pose file? Is this one of the .csv or .h5 file that was created by deeplabcut?

Thanks,
Bram

**Comment by KLuxem** [comment]
Thank you Bram for bringing this up. 
To this point it is not necessary to put your pose-estimation.csv file into the videos/pose-estimation folder. This was for an automatic alignment from global to egocentric virtual marker coordinates which is currently not implemented. 
I will take this note out of the demo.py file. This should resolve this issue. 

Cheers,
Kevin

**Comment by bramn22** [comment]
Okay, thank you.
