### ISSUE TITLE
community errors / endless loop

### ISSUE THREAD

**Issue by alexcwsmith** [LINCellularNeuroscience/VAME#41]
Hey Kevin,
The update looks great, excited to try it out. But on plotting vame.community(config, show_umap=False), I get this error:

```
AttributeError: 'FigureManagerBase' object has no attribute 'window'
```
this is fixed by specifying to use Qt5 as the window manager with:
```
import matplotlib
matplotlib.use('Qt5Agg')
```
but that window is still very glitchy and the 'save' button doesn't work. I'm using qt=5.12.9. Can you let me know if you use a different version of Qt?

I also get an error in true_divide when I run this, and it gets stuck in an endless loop (i.e. inputting 'yes' does not break the loop). I looked at the code in community_analysis.vame
```
/d1/studies/VAME/vame/analysis/community_analysis.py:56: RuntimeWarning: invalid value encountered in true_divide
  transition_matrix = adjacency_matrix/row_sum[:,np.newaxis]
/d1/studies/VAME/vame/analysis/tree_hierarchy.py:66: RuntimeWarning: divide by zero encountered in double_scalars
  cost = motif_norm[i] + motif_norm[j] / np.abs(transition_matrix[i,j] + transition_matrix[j,i] )
/d1/studies/VAME/vame/analysis/tree_hierarchy.py:66: RuntimeWarning: invalid value encountered in double_scalars
  cost = motif_norm[i] + motif_norm[j] / np.abs(transition_matrix[i,j] + transition_matrix[j,i] )

Where do you want to cut the Tree? 0/1/2/3/...1
[[3, 2, 12, 7, 11, 6, 5, 0, 4, 10, 14], [13, 9, 1, 8]]


Are all motifs in the list? (yes/no/restart)yes

Where do you want to cut the Tree? 0/1/2/3/...1
[[3, 2, 12, 11, 7, 6, 5, 0, 4, 10, 14], [13, 9, 8, 1]]


Are all motifs in the list? (yes/no/restart)yes
```

From looking at the "while flag_1=='no'" loop I can't figure out why the logic is breaking there, but I can tell that isn't the expected behavior. But if I specify the cut_tree parameter in the vame.community function call then it seems to break Qt completely, nothing is displayed and the kernel dies (that again may be a Qt issue).

Very strangely, if I run the code in create_community_bag on it's own, not in a function, it works as expected IF I comment out the plt.pause(0.5) line. But having that line commented out while running it from the vame.community() function still gets stuck in an endless loop. I'm officially stumped...

**Comment by alexcwsmith** [comment]
Ah so I just realized this is displaying a tree for every individual video. So a print statement with the video ID will be very helpful. If i continue the sequence of "2,yes" etc down the line, I eventually get to:

```
IndexError: index 14 is out of bounds for axis 0 with size 14
```

so not all motif_usage.npy files are actually shape (n_cluster,n_cluster). You previously merged my PR https://github.com/LINCellularNeuroscience/VAME/pull/24 that fixed that problem, is there a reason that solution for ensuring all empty motifs are accounted for doesn't work in the pose_segmentation version of get_motif_usage?

**Comment by KLuxem** [comment]
Hi Alex,

thanks for reporting these bugs. To be honest the community detection code is somewhat more experimental at this point and we thinking of implementing a GUI kind of version where you can just select the motifs you want to have in a community based on the tree. 

Nevertheless, I will look into the script again and see if I can arrange some improvements for the current version.

Regarding the last question, motf_usage.npy is supposed to be in the shape of (n_cluster), means if you decide for 15 cluster you should have 15 entries in this array. 

Thank you again Alex, I'll post here when I have a good fix for the reported bug

**Comment by Virginia9733** [comment]
Hi Alex, 

I am facing the same issue. 
When I used vame.community(config, show_umap=False) in google colab, I get this error:

AttributeError: 'FigureManagerBase' object has no attribute 'window'

Following your solution, 
import matplotlib
matplotlib.use('Qt5Agg')

I got this error message: 
AttributeError: 'FigureManagerBase' object has no attribute 'window'

I assume it because colab did not support GUI

Then I moved to my local computer, MacOS Catalina without GPU. Following your suggestions, but still, I got the same error message:
AttributeError: 'FigureManagerMac' object has no attribute 'window'

Could you kindly tell me how to solve this issue? Many thanks!

**Comment by Virginia9733** [comment]
I solved the QtAgg problem by:

import matplotlib
import matplotlib.pyplot as plt
plt.switch_backend('Qt5Agg')
print(matplotlib.get_backend())

result：
Qt5Agg

Now I could use vame.community

Thanks!
