### ISSUE TITLE
keyError:'random_state_kmeans: '

### ISSUE THREAD

**Issue by ZiyiZhang0912** [LINCellularNeuroscience/VAME#43]
Hello, first of all thank you very much for this excellent project, which will provide a lot of help for the data analysis of my project.

VAME created a new project on my project data, and the training and evaluation network were all running successfully, but the following error was encountered when running vame.pose_segmentation():

<img width="608" alt="fa8899ce8a920848b6ac5914d3e4c29" src="https://user-images.githubusercontent.com/62039483/113119444-076d4d80-9243-11eb-869f-273c8941df43.png">

Because I am not familiar with your code, I cannot know the reason for this error. I hope to get your help. 

I think it may be caused by which parameter in my config.yaml does not match my project data. Therefore, I would also like to ask if there is a document that details the role of the parameters in the config.yaml file and how to modify the configuration, so that I can know that I should how to adjust which parameters to get better performance according to my project data (training set size, etc.) .

Very thanks for any reply and suggestions!

**Comment by KLuxem** [comment]
Hi, happy to hear that you like the project! 

It seems that your `config.yaml` is missing the key `random_state_kmeans: 42`. 
We added a few more extensions to our config file and I just pushed a function to automatically update the config. 
So you can just pull the project and then call the following function:

`vame.update_config(config)`

This will bring your config file to the up to date version and everything should run smoothly. 

Moreover, you can find a guide to all parameter in `config.yaml` [here](https://github.com/LINCellularNeuroscience/VAME/wiki/2.-VAME-config.yaml). 

I hope this helps!

**Comment by ZiyiZhang0912** [comment]
> Hi, happy to hear that you like the project!
> 
> It seems that your `config.yaml` is missing the key `random_state_kmeans: 42`.
> We added a few more extensions to our config file and I just pushed a function to automatically update the config.
> So you can just pull the project and then call the following function:
> 
> `vame.update_config(config)`
> 
> This will bring your config file to the up to date version and everything should run smoothly.
> 
> Moreover, you can find a guide to all parameter in `config.yaml` [here](https://github.com/LINCellularNeuroscience/VAME/wiki/2.-VAME-config.yaml).
> 
> I hope this helps!


Hello, thank you very much for your reply, it is very useful to me. I can now run vame.pose_segmentation() normally.

Then I wanted to visualize the results, so I tried to execute vame.visualization(config), but got this error:

<img width="610" alt="b17f9a72b76b3fbb2b55fbcd7a51b8c" src="https://user-images.githubusercontent.com/62039483/113238513-83b36f80-92db-11eb-86c7-bd04d2acb20f.png">

Then I canceled the setting of the parameter label="motif" and re-run. Although there were no more errors, the running process and results made me unable to understand. This is the running process and the result:

<img width="372" alt="d936cda7f9236c24fb8161b48149268" src="https://user-images.githubusercontent.com/62039483/113238647-c07f6680-92db-11eb-8504-8bc6f612aa18.png">

The following are the files that appeared in my VAME folder after running the above steps:

<img width="458" alt="21f607750b3394c68cc42ec6e472e49" src="https://user-images.githubusercontent.com/62039483/113238777-03413e80-92dc-11eb-9426-eb58e8c09b02.png">

It is still a .npy file, and the name of the folder is community, but I did not run vame.community() or vame.community_videos()... I am not sure if my run results are what should be obtained correctly in the visualization step. .. And in my understanding, visualization will get image results instead of .npy results.

Thank you very much for your reply and any help.

**Comment by pavolbauer** [comment]
Hi, the above error with regards to the label variable was fixed with the last commit to the master repo: https://github.com/LINCellularNeuroscience/VAME/commit/3afe88cae30a185676b794dbc11c0641ae07a13a
Please pull the repo again, than the code should run smoothly again. I close the issue, please reopen again if needed.
Best, Pavol
