### ISSUE TITLE
Wrong cost expression in merge_func

### ISSUE THREAD

**Issue by pineider** [LINCellularNeuroscience/VAME#44]
The cost expression in merge_func (tree_hierarchy.py:66) seems to miss parentheses around the numerator, based on equation (21) in Luxem et al. (2020).
Furthermore, the cases of zero numerator and/or denominator should be explicitly handled.

**Comment by pavolbauer** [comment]
Dear Giuseppe,

Thanks for that issue report. Indeed, a bracket is missing around that numerator.
We are preparing a fix including zero exception handling for the equation in tree_hierarchy.py:66 in the days to come.

Best,
Pavol

**Comment by pineider** [comment]
Dear Pavol,

Thanks for the fix and for VAME!

Best,

Giuseppe

**Comment by pavolbauer** [comment]
You're welcome! The fix is comitted now and I am closing the issue.

Best,
Pavol
