### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by jdohn15** [LINCellularNeuroscience/VAME#45]
When I run 'vame.train_model(config)' I get this error. Is there a fix for "RuntimeError: CUDA error: out of memory" on a graphics card that only has 6gb of memory?
I am new to this and I am curious as to if there is any workaround for having a lousy graphics card.

Thanks.

**Comment by KLuxem** [comment]
Hi. 
An easy fix for this is usually to lower the batch size of your model. You can find this parameter in your config.yaml and adjust it accordingly. Maybe for starters try half of the batch size. 

I hope this helps,
Kevin

**Comment by jdohn15** [comment]
> Hi.
> An easy fix for this is usually to lower the batch size of your model. You can find this parameter in your config.yaml and adjust it accordingly. Maybe for starters try half of the batch size.
> 
> I hope this helps,
> Kevin

Thanks! I gave that a try decreasing the batch size to 128 along with decreasing the crop size to 50x50 just to test it out and it worked! Will I run into any issues with the crop size?

**Comment by KLuxem** [comment]
Depending on your data you should leave the crop size to the original value. Moreover, this does not affect your GPU memory. A too low crop size will result in to a egocentrical aligned time series which is cut at the top and bottom. 

With this I will close the issue and hope VAME will bring you interesting results!
