### ISSUE TITLE
Could not create trainset

### ISSUE THREAD

**Issue by Virginia9733** [LINCellularNeuroscience/VAME#46]
Hi,

I try to run VAME locally on my laptop, following the instruction, and could successfully install and import VAME in the conda environment.
However, when try to convert .csv to .npy using the vame.csv_to_npy(), it runs without erroe but I could not find the .npy file in de working directory.
Then I try to run vame.create_trainset(config)
I got the error message below.

>>> vm.csv_to_numpy(config, datapath='/Users/virginiali/VAME/Muhang-VAME-Project-May14-2021/videos/pose_estimation')
Your data is now ine right format and you can call vame.create_trainset()
>>> vm.create_trainset(config)
Creating training dataset...
Using robust setting to eliminate outliers! IQR factor: 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/virginiali/VAME/VAME-master/vame/model/create_training.py", line 186, in create_trainset
    traindata(cfg, files, cfg['test_fraction'], cfg['num_features'], cfg['savgol_filter'])
  File "/Users/virginiali/VAME/VAME-master/vame/model/create_training.py", line 66, in traindata
    X = np.concatenate(X_train, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

Could anyone kindly give me some suggestions to fix it? Many thanks!

I am using  MAC airbook, macOS Catalina 10.15.7

**Comment by Virginia9733** [comment]
Solved, thanks! There is something wrong when I create the project and the video was not copied, now it fixed.

**Comment by jelrod14** [comment]
I realize this is quite late lol, but how did you end up solving this issue? I have tried copying my video into the videos folder, but still nothing. Thanks!

**Comment by LIU-Alessia** [comment]
@jelrod14 I have also encountered this problem, have you solved?
