### ISSUE TITLE
.npy file structure

### ISSUE THREAD

**Issue by bramn22** [LINCellularNeuroscience/VAME#5]
Hi, 

For the files that have to be added to the /data folder, it seems that .npy files are expected. How should the pose estimation information be organized in these files (rows=frames, columns=x or y coordinate of a bodypart)? 
Is there a script that makes the automatic conversion from e.g. Deeplabcut .csv files to .npy files?

Thanks, 
Bram

**Comment by KLuxem** [comment]
Hi Bram,
yes, this is basically the entry point to use VAME. The pose estimation information is organized like you said, i.e. rows corresponding to the frame while columns are the x and y coordinates of every bodypart. You can find an example of how the videoname-PE-seq.npy should look like in our VAME/examples/ folder. It is important that your data is egocentrically aligned which is not the case if you use open-field data. If your experiment is for example with a head-fixed animal, your data is already egocentric.

We don't have a script available to automatically converse pose-estimation data to .npy files. However, a simple solution would look like this (if your data is a priori egocentric i.e. a restrained setup):

> Read in your .csv file, skip the first two rows and create a numpy array

`data = pd.read_csv("/Your-VAME-Project/videos/pose-estimation/video-1-PE.csv", skiprows = 2)`
`data_mat = pd.DataFrame.to_numpy(data)`
 `data_mat= data_mat[:,1:] `

> get the number of bodyparts, their x,y-position and the confidence from DeepLabCut

`bodyparts = int(np.size(data_mat[0,:]) / 3)`
`positions = []`
`confidence = []`
`idx = 0`
`# Start FOR loop`
`for i in range(bodyparts):`
`positions.append(data_mat[:,idx:idx+2])`
`     confidence.append(data_mat[:,idx+2])`
`      idx += 3`     
`# End FOR loop`    
`body_position = np.concatenate(positions, axis=1)`
`con_arr = np.array(confidence)`

> Find low confidence and set them to NaN (vame.create_trainset(config) will interpolate these NaNs)

`body_position_nan = []`
`idx = -1`
`# Start FOR loop`
`for i in range(bodyparts*2):`
`if i % 2 == 0:`
`idx +=1`
`seq = body_position[:,i]`
`seq[con_arr[idx,:]<.99] = np.NaN`
`body_position_nan.append(seq)        `
`# End FOR loop`    
`final_positions = np.array(body_position_nan)`

> save the final_positions array with np.save()

`np.save("/Your-VAME-Project/data/video-1/video-1-PE-seq.npy", final_positions)`

I added this script here: VAME/examples/demo_csv_to_npy.py. If there is still some confusion let me know and I hope this helps to resolve this issue.

Cheers,
Kevin

**Comment by bramn22** [comment]
Great, that works.
Thanks!
