### ISSUE TITLE
Program is terminated because you tried to allocate too many memory regions.

### ISSUE THREAD

**Issue by surin009** [LINCellularNeuroscience/VAME#51]
Hello, 

I installed VAME early last week using the git clone feature shown in your main page. I am able to successfully follow the workflow until the pose_segmentation step. When I select multiple video/excel files for training, everything works until I try to use the pose_segmentation function, where I get an error "Program is terminated. Because you tried to allocate too many memory regions" and then the Anaconda powershell window I'm running on terminates out of Ipython and the VAME environment. 

If I edit the config file after training and use only one video file at a time, I can get get the pose_segmentation and the latter functions to work, so I think it may be potentially be an issue with setting up parallel computing during analysis? For reference, I'm running on a GeForce RTX 2080 Super GPU with 8 Gb memory and the RAM onboard the computer is 96 gigs of ram, running on Windows 10 OS. 

Here is an example of what the "error" looks like during the pose_segmentation function execution. It looks like it's able to analyze the pose predictions, and then quits right after. Thanks for your help!

![image](https://user-images.githubusercontent.com/44507739/119206471-de0db880-ba60-11eb-8055-817cdc265631.png)

**Comment by pavolbauer** [comment]
Dear Surin009,

It might be that you are running out of your GPU memory. You could try to reduce your batch size in your config.yaml and see if that solveds the problem.

See this perhaps related issue here: https://github.com/LINCellularNeuroscience/VAME/issues/45
And also in the OpenBLAS repository: https://github.com/xianyi/OpenBLAS/issues/539

Best,
Pavol

**Comment by pavolbauer** [comment]
I'm closing this issue now because it's rather related to Pytorch/openBlas. Feel free to reopen in case more support from our side is needed.

**Comment by outlace** [comment]
I also had this error but indeed lowering the batch size from 256 to 32 solved it. Using Nvidia RTX A5000
