### ISSUE TITLE
Further Analysis?

### ISSUE THREAD

**Issue by jdohn15** [LINCellularNeuroscience/VAME#52]
Is it possible to get a output of how many times a motif is repeated? I am trying to compare the amount of times a animal repeats a behavior between some groups and was wondering if it was possible with this program?

Thanks,

John

**Comment by pavolbauer** [comment]
Dear John,

Yes, that is possibe. For this; train the model according and segment the behavior according to the workflow instructions.
Make sure you use the same k-means model for all your invidual animal data.

Afterwards go to your VAME/results folder and load the "XX_km_label_video_X.npy" arrays for each video. For each of them, you can get the number of frames where each behavior was detected using for example, the np.histogram() function. To get the instance count of each behavior your have to code a loop that detects sequences of equal integers throughout the same vector. Maybe some inspiration can be found here;
https://stackoverflow.com/questions/33028481/find-extract-a-sequence-of-integers-within-a-list-in-python

Please reopen the issue if this advice was not enought to solve the issue.
Best,
Pavol
