### ISSUE TITLE
How to put labels of motifs and communities in the GIF?

### ISSUE THREAD

**Issue by Virginia9733** [LINCellularNeuroscience/VAME#53]
I have generated the png by using:
vame.gif(config, pose_ref_index=[0,5], subtract_background=True, start=0, length=500, max_lag=30, label='community', file_format='.mp4', crop_size=(300,300))

However, unlike the GIF in the github frontpage, there is no lables showing motifs and communities, and the movement of the animal is not that smooth. 
k-means = 15, cut_tree = 2

The GIF looks like this:
https://drive.google.com/file/d/15LVOY8ps4VKlgMgB4uY-VTvabwNYH1cM/view?usp=sharing

How to put labels of motifs and communities in the GIF?

Many thanks!

**Comment by KLuxem** [comment]
This is absolutely right. But if you want to see the community number and the motif label, you can just go ahead and uncomment line 50 in the gif creation [script](https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/analysis/gif_creator.py).

We are currently working towards a GUI for the community analysis, which we help to name communities e.g. walk, rear etc and then we have this also ready for our gif creation script. 

I hope this helps and let me know if there are any issues.
Kevin

**Comment by Virginia9733** [comment]
Thank you very much, however, I followed your suggestion to uncomment line 50 in gif_create.py, it doesn't work. The png
in the folder gif_frames is still without labels of motif and communities labels.

![video-1gif_60](https://user-images.githubusercontent.com/61534754/120431150-ad0b7d00-c3aa-11eb-901d-b52747af08cd.png)

**Comment by Virginia9733** [comment]
I have a new error...When I try to create a gif using my own video, after computing background images, it said, killed 9

![Screen Shot 2021-06-05 at 1 09 04 PM](https://user-images.githubusercontent.com/61534754/120880856-74181600-c5ff-11eb-9401-d6798a1df89d.png)

I have been a bit exhausted trying to figure it out, and have tried several times, each time it costs me 2.3-3 hours to compute the background images. Any help would be much appreciated!

**Comment by Virginia9733** [comment]
I used the demo video to create a gif with labels of motif and community, however, I don't know in which script could Iabel motif and community. I uncomment line 50 in gif_creator.py, the error messages said:
NameError: name 'lbl' is not defined

![Screen Shot 2021-06-06 at 2 23 12 PM](https://user-images.githubusercontent.com/61534754/120914817-0fc68680-c6d3-11eb-9a7f-f3d1f5db3381.png)

**Comment by pavolbauer** [comment]
Hi Virgina,

You can replace "lbl" with "i" and "motifs" with "clabel", which is the community label.
At the moment we are working on a GUI for community assignment+labeling, as soon as this code will be released the toolbox (including the gif creator) will recieve an update which will these steps easier.

Best,
Pavol
