### ISSUE TITLE
How to deal with multi-animals?

### ISSUE THREAD

**Issue by Virginia9733** [LINCellularNeuroscience/VAME#54]
The camera recorded 4 mice simultaneously during a 30 min open-field task. I have used DeepLabCut to extract the position of each animal. How could I use VAME to analyze their behavior motifs based on the .csv file created by DLC?

Many thanks!

**Comment by pavolbauer** [comment]
Hi,
When using DeepLabCut with multi-animal support (maDLC) you will obtain a little differently structured CSV files as a result.
We don't provide a specific parser yet for this files at the moment, but you could easily modify them using e.g. Excel to match the structure of CSV files obtained from single-animal DLC and then use those as input for VAME.egocentric_alignment().
However, I mark the parser von maDLC files as a feature request for the next major update of VAME.
Best,
Pavol

**Comment by Virginia9733** [comment]
Thank you very much!
