### ISSUE TITLE
VAME runs on google colab?

### ISSUE THREAD

**Issue by aXcELLcore** [LINCellularNeuroscience/VAME#55]
I know that to date it can be difficult to install in the cloud since there is no launch of pip, but I would like to know if there is already any other way to work with VAME that is not locally since the use of GPU is an important limiting factor for being able to use this software

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi Axel, I just found this related issue #47 
Hope it helps

**Comment by aXcELLcore** [comment]
Thank you very much Guillermo, I think it is just what I needed, you have made me very happy

**Comment by KLuxem** [comment]
Thank you Guillermo, I will close this issue then
