### ISSUE TITLE
Assigning labels to clusters

### ISSUE THREAD

**Issue by elenael97** [LINCellularNeuroscience/VAME#63]
Hello,

I hope it is ok that I am posting two questions in the row, I did not want to ask two unrelated questions in the same issue.

What I was interested in is whether there is any way for me to know why exactly VAME decided to group specific behaviours together? I can see from your publication that when clusters were formed by the program, you would assign the labels to the communities of motifs, but this would require a subjective judgement about what VAME found. I was wondering if there is any other way to find out what unites specific communities, let's say a specific skeleton structure, perhaps a pause in movement or acceleration... Obviously, I understand that VAME won't just tell me that the specific community corresponds to grooming, but I was wondering if there is any way to define the characteristics of clusters without just deciding on your own.

**Comment by kvnlxm** [comment]
Thank you @alexcwsmith, this is very much the reason and so far, this is not solved in any of the available tools. 

Cheers,
Kevin
