### ISSUE TITLE
vame.csv_to_npy pose confidence is hard coded as 0.99 

### ISSUE THREAD

**Issue by stowerslab** [LINCellularNeuroscience/VAME#67]
i was wondering why vame.create_trainset() was throwing empty array errors and found out that one of my columns in the NPY file was still empty even when i lowered the pose confidence threshold

i think line 5 in the code block below is the issue

        for i in range(bodyparts*2):
            if i % 2 == 0:
                idx +=1
            seq = body_position[:,i]
            seq[con_arr[idx,:]<.99] = np.NaN
            body_position_nan.append(seq)

**Comment by kvnlxm** [comment]
Thank you for bringing this up. The `csv_to_numpy.py` function is now updated and creates now the correct representation to create the training set and train VAME.

Cheers,
Kevin
