### ISSUE TITLE
Possible NumPy Version issue in createTrainset()

### ISSUE THREAD

**Issue by JensBlack** [LINCellularNeuroscience/VAME#8]
Hi Kevin,
Hi Pavel,

Quick report, so others might find it. This is not a VAME issue but might be connected to the installation process. Please feel free to remove it, if you think it is unnecessary!

I ran into an error when creating the trainset using `numpy 1.18.1`.
This seems to be connected to np.load()
`ValueError("Object arrays cannot be loaded when "ValueError: Object arrays cannot be loaded when allow_pickle=False")`

A quick google suggested a version conflict: [Stackoverflow link](https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa)
Apparently newer versions of NumPy do not have allow_pickle set to True.

Downgrading NumPy to 1.16.1 solved the issue for me.

`pip install numpy==1.16.1`
Although the thread suggests another work around.

best,
Jens

**Comment by JensBlack** [comment]
Just a report, so I will close it.

**Comment by KLuxem** [comment]
Thank you Jens for reporting this!

**Comment by JensBlack** [comment]
Running the Demo file (after reverting to the new numpy version 18.X again) did not raise the same issue. So there might be an issue with my original file or the conversion!
