### ISSUE TITLE
possible bug in code in align_egocentrical.py

### ISSUE THREAD

**Issue by WeissShahaf** [LINCellularNeuroscience/VAME#80]
def alignment(path_to_file, filename, pose_ref_index, video_format, crop_size, confidence, use_video=False, check_video=False):
    
    #read out data
    data = pd.read_csv(os.path.join(path_to_file,'videos','pose_estimation',filename+'.csv'), skiprows = 2)
    data_mat = pd.DataFrame.to_numpy(data)
    data_mat = data_mat[:,1:] 
    
line 258 in align_egocentrical.py, throws out the first column (0):
    data_mat = data_mat[:,1:] 
    so the first X coordinates in the DLC csv file are discarded.

**Comment by kvnlxm** [comment]
Hi and thank you for bringing this up. This part of the code takes care of the first column, which usually is the index of the csv file, so `1, 2, 3, ...., N` up to the number of frames N. But if this is for some reason not true for your data, you should adjust this part in your code. 

Cheers,
Kevin
