### ISSUE TITLE
 Visualizing the network 

### ISSUE THREAD

**Issue by yangyuke001** [LINCellularNeuroscience/VAME#84]
hi，
I have visualized the rnn network，but I am not confident about it's accuracy. 
Would you mind check it ？
Here is the picture:
![Digraph gv 0](https://user-images.githubusercontent.com/27425366/174033995-cf004e07-33ed-48d4-9c84-e37bd5ffdeb1.png)

And in netron tool, I got the results:
![VAME_3d-vame_epoch_150 pkl](https://user-images.githubusercontent.com/27425366/174230647-db881f0a-2ffd-4a44-afbd-92feb4835f19.png)

And if its correct,I can push my code , it runs on command:
`vame.vis_rnn_network(config)`

**Comment by pavolbauer** [comment]
Hi,

That's pretty cool!
The graph looks good to me on the first view, feel free to make the PR, than we can review it, too.

Best,
Pavol

**Comment by yangyuke001** [comment]
@pavolbauer 
Hi,

I have pushed the code, please check it!

Best,
Yangyuke
