### ISSUE TITLE
Command Line Coding With Linux

### ISSUE THREAD

**Issue by emdbell17** [LINCellularNeuroscience/VAME#86]
I'm having a lot of syntax issues when command line coding in linux that do not make sense. I'm new to coding but wanted to ask if VAME is meant to be used in command line or a jupyter notebook. I successfully installed and created the conda environment but can't seem to do much more!

**Comment by pavolbauer** [comment]
Hi, VAME is a python toolbox, you can type the commands into a python interpreter (e.g. Spyder) or jupyter notebook. An exemplary file to run VAME can be found [here](https://github.com/LINCellularNeuroscience/VAME/blob/master/examples/demo.py) and the description of the workflow is [here](https://github.com/LINCellularNeuroscience/VAME/wiki/1.-VAME-Workflow). 
Best
Pavol
