### ISSUE TITLE
Error: '<=' not supported between instances of 'str' and 'ScalarFloat'

### ISSUE THREAD

**Issue by emdbell17** [LINCellularNeuroscience/VAME#87]
I have two multiple animal (two mice) pose estimation videos with their corresponding csv files. Each csv file has 10 points for each animal in each csv file. When I run "vame.egocentric_alignment(config, pose_ref_index=[0,19], crop_size=(300,300), use_video=False, video_format='.mp4', check_video=False)", I receive the error listed in the title. I'm not sure if vame supports multi animal pose estimation or not?

**Comment by kvnlxm** [comment]
Hi! It seems like your error comes from a wrong specification of the `pose_ref_index`. Please see isse #77 for this. 

To use VAME with multiple animals, just create for each animal their own .csv file as in our example and start from there. Once you are more comfortable with the tool mechanics, you can of course introduce other factors like distance between animals etc and try to learn an embedding from there. I would also like to point you to this recent [paper](https://arxiv.org/abs/2206.07041) as well as to the [MABe challenge](https://sites.google.com/view/mabe22/home) for further information on multi animal behavior representations. 

In the end it all comes down of how you prepare your input data to VAME, maybe you need to tinker a bit with the preparation.

**Comment by kvnlxm** [comment]
Closing this issue for now.
