### ISSUE TITLE
RuntimeError: Vame.rnn_model()

### ISSUE THREAD

**Issue by JensBlack** [LINCellularNeuroscience/VAME#9]
Hi,
I tried to train the model using the code steps provided in `demo.py` but ran into an issue:
Can you help? 

```
# Train rnn model:
vame.rnn_model(config, model_name='VAME', pretrained_weights=False, pretrained_model='pretrained')
```
Console Output:
```
Train RNN model!
Using CUDA
GPU active: True
GPU used: GeForce RTX 2070 with Max-Q Design
Latent Dimensions: 30, Beta: 1, lr: 0.0005
Initialize train data. Datapoints 45911
Initialize test data. Datapoints 11477
Epoch: 1
Train: 

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/schwa/PycharmProjects/VAME/examples/demo.py", line 31, in <module>
    vame.rnn_model(config, model_name='VAME', pretrained_weights=False, pretrained_model='pretrained')
  File "C:\Users\schwa\PycharmProjects\VAME\vame\model\rnn_vae.py", line 442, in rnn_model
    TRAIN_BATCH_SIZE)
  File "C:\Users\schwa\PycharmProjects\VAME\vame\model\rnn_vae.py", line 256, in train
    kmeans_loss = cluster_loss(latent.T, kloss, klmbda, bsize)
  File "C:\Users\schwa\PycharmProjects\VAME\vame\model\rnn_vae.py", line 186, in cluster_loss
    _ ,sv_2, _ = torch.svd(gram_matrix)
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 14)
```

best,
Jens

**Comment by JensBlack** [comment]
The error did not occur when running the training with the demo file `video-1-PE-seq.npy`

**Comment by JensBlack** [comment]
Thank you, Kevin. After the extensive search and the discussion with you via email, I was able to solve that issue.

**Apparantly, I forgot to align my data egocentrical which started a whole barrage of problems.** I tried several different approaches to rule out any conversion issues but could not find any.
It is weird that a different set of numbers creates that issue, but my transformed data is working.

I want to write down a few things from my search that were weird:
 The `File-PE-seq.npy` file created by your demo code was structure the same, but was dtype object rather than float64.
I was able to create a training set with it which was dtype float64.
The content of the file was shaped like this:
`[[546.5120849609375 545.6234741210939 544.8563232421875 ...
  329.7113037109375 330.50433349609375 332.00457763671875], ...]`
while the demo set only had rounded numbers like this:
`[[150. 150. 150. ... 150. 150. 150.], ...]`
Both are float and in the same range.

After transforming my original data, I ran in a totally new error that i will discuss in a seperate issue that is also connected to the values of the file. Very interesting!
Again, Thank you for the quick response.
I am still wondering what caused the error.

**Comment by pavolbauer** [comment]
Hi Jens,
Again, thans for trying out VAME and reporting on issues you found in the code!
The error in the SVD solver probably happened because the use of un-aligned marker time series produces a Z matrix that is ill-conditioned, i.e. contains values spaning many orders of magnitude.
We think about adding a check on the condition number of Z in a future release of VAME in order to ensure exception handling prior to the solver call. Thanks for pointing this out.
Best,
Pavol
