### ISSUE TITLE
MotionMapper Comparison in Paper

### ISSUE THREAD

**Issue by shreyask3107** [LINCellularNeuroscience/VAME#92]
Hi @kvnlxm , I am still confused about using Mouse Poses for MotionMapper.
Did you create a distance matrix as in https://github.com/PrincetonUniversity/MouseMotionMapper?
Further creating PCA projections on them to be further used for wavelet transform, T-SNE and watershed segmentation?

The watershed segmentation results in identifying peaks over a 2-dimensional embedding of T-SNE. But how did you utilize this for temporal segmentation?

**Comment by pavolbauer** [comment]
Hi there,
We used the following script to import the DLC series into MotionMapper: https://github.com/DeepLabCut/DLCutils/tree/master/DLC_2_MotionMapper
The script is applying the MotionMapper workflow (T-sne, watershed) on the Fourier bands of the DLC signal.
Make sure you set the parameters in the beginning of the script and vary the perplexity a bit to find the best setting for your data.
Best,
Pavol
