### ISSUE TITLE
VAME First Step Issues 

### ISSUE THREAD

**Issue by sarahy191** [LINCellularNeuroscience/VAME#93]
After i type the first  step command it gives me an error saying "quote" can anyone help me out. 

Thanks!

**Comment by sarahy191** [comment]
![image](https://user-images.githubusercontent.com/116017420/196975355-760d6baa-8ee1-498f-9b0e-38484d7ad4c8.png)

**Comment by kvnlxm** [comment]
Hi,

After activating the environment it is easiest to work in an IDE like Spyder. These functions are not meant to run via a terminal. 

`conda install -c anaconda spyder`

**Comment by sarahy191** [comment]
Hi
I installed spyder with the command in the terminal, however, i am getting: 
zsh: unknown sort specifier

I tried to make the video files name without space but that didn't help.
here is what i executing:
config = vame.init_new_project(project='Sarahy-VAME-Project', videos=['/Desktop/indivudal research project/videos trial/Panx1a1','/Desktop/indivudal research project/videos trial/Panx1a2','/Desktop/indivudal research project/videos trial/Panx1a3'], working_directory='/Desktop/indivudal research project/videos trial/', videotype='.avi')

**Comment by sarahy191** [comment]
Sorry i sent wrong error, this what i get from Spyder

===============================================

config = vame.init_new_project(project='Sarahy-VAME-Project', videos=['/Desktop/indivudal research project/videos trial/Panx1a 1','/Desktop/indivudal research project/videos trial/Panx1a2','/Desktop/indivudal research project/videos trial/Panx1a3'], working_directory='/Desktop/indivudal research project/videos trial/', videotype='.avi')
Traceback (most recent call last):

  File "/var/folders/05/d8hg2t_n7rvg_r2fdrqxhwl80000gn/T/ipykernel_49589/2510441784.py", line 1, in <module>
    config = vame.init_new_project(project='Sarahy-VAME-Project', videos=['/Desktop/indivudal research project/videos trial/Panx1a 1','/Desktop/indivudal research project/videos trial/Panx1a2','/Desktop/indivudal research project/videos trial/Panx1a3'], working_directory='/Desktop/indivudal research project/videos trial/', videotype='.avi')

NameError: name 'vame' is not defined

**Comment by sarahy191** [comment]
Hi, Any help really appreciated.

below is what i get when i launch spyder from the Terminal (please note, I tried to create new VAME called VAMEE by changing the VAME.ymal to create new one as some rationals says the error because i have two labs. so i created new one with new name but that didn't help.

===========================================
Python 3.7.13 (default, Oct 18 2022, 13:40:53)
Type "copyright", "credits" or "license" for more information.

IPython 7.31.1 -- An enhanced Interactive Python.

Conda config = VAMEE.init_new_project(project='Sarahy-VAME-Project', videos=[“/Desktop/indivudal research project/videos trial/Panx1a 1”,”/Desktop/indivudal research project/videos trial/Panx1a2”,”/Desktop/indivudal research project/videos trial/Panx1a3”], working_directory=”/Desktop/indivudal research project/videos trial/”, videotype=”.avi”)
  File "/var/folders/05/d8hg2t_n7rvg_r2fdrqxhwl80000gn/T/ipykernel_23871/4137163199.py", line 1
    Conda config = VAMEE.init_new_project(project='Sarahy-VAME-Project', videos=[“/Desktop/indivudal research project/videos trial/Panx1a 1”,”/Desktop/indivudal research project/videos trial/Panx1a2”,”/Desktop/indivudal research project/videos trial/Panx1a3”], working_directory=”/Desktop/indivudal research project/videos trial/”, videotype=”.avi”)
               ^
SyntaxError: invalid syntax

**Comment by kvnlxm** [comment]
Hi,

Would you have a lab mate or friend who has some experience with Anaconda, Spyder or Python in general? I would recommend you take a small tutorial on how to setup virtual environments in Anaconda as well as some general Python and run them in Spyder.  Your errors, unfortunately, arise from the lack of knowledge with these tools but I am sure you can easily pick it up, or let someone show you how to get started. 

For example, in Spyder you need to first write `import vame`. If you still get the error `NameError: name 'vame' is not defined`, please select the workspace in Spyder where you have VAME downloaded. Below I included some example images:

![anaconda](https://user-images.githubusercontent.com/36508427/197476616-e49cfd6a-eed4-49f7-a4f6-6e5c4c3e3675.PNG)
![spyder](https://user-images.githubusercontent.com/36508427/197476641-4b0b442e-3d2c-4e25-b302-5915ca06358e.PNG)
![folder](https://user-images.githubusercontent.com/36508427/197476648-0c77808d-99cc-4876-bb5d-0c4ea7cc50d2.PNG)
