### ISSUE TITLE
 File "<__array_function__ internals>", line 180, in concatenate ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by camaristajp** [LINCellularNeuroscience/VAME#97]
Creating training dataset...
Using robust setting to eliminate outliers! IQR factor: 4
Creating trainset from the vame.csv_to_numpy() output
Traceback (most recent call last):
  File "c:/Users/kyleb/VAME/vame/initialize_project/demo.py", line 44, in <module>
    vame.create_trainset(config, check_parameter=False)
  File "C:\Users\kyleb\AppData\Local\Programs\Python\Python38\lib\site-packages\vame-1.0-py3.8.egg\vame\model\create_training.py", line 297, in create_trainset      
  File "C:\Users\kyleb\AppData\Local\Programs\Python\Python38\lib\site-packages\vame-1.0-py3.8.egg\vame\model\create_training.py", line 239, in traindata_fixed      
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by xiaoli26** [comment]
the same to me

**Comment by xiaoli26** [comment]
Your data is now ine right format and you can call vame.create_trainset()
Your data is now ine right format and you can call vame.create_trainset()
Traceback (most recent call last):
  File "D:/anipose/VAME/examples/demo.py", line 44, in <module>
    vame.create_trainset(config, check_parameter=False)
  File "D:\anipose\VAME\vame\model\create_training.py", line 297, in create_trainset
    traindata_fixed(cfg, files, cfg['test_fraction'], cfg['num_features'], cfg['savgol_filter'], check_parameter)
  File "D:\anipose\VAME\vame\model\create_training.py", line 239, in traindata_fixed
    X = np.concatenate(X_train, axis=0).T
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
Creating training dataset...
Using robust setting to eliminate outliers! IQR factor: 4
Creating trainset from the vame.csv_to_numpy() output

**Comment by pavolbauer** [comment]
Hi, could you please specify the dimensions of your input data.

**Comment by Zkkdxbg** [comment]
> Your data is now ine right format and you can call vame.create_trainset() Your data is now ine right format and you can call vame.create_trainset() Traceback (most recent call last): File "D:/anipose/VAME/examples/demo.py", line 44, in vame.create_trainset(config, check_parameter=False) File "D:\anipose\VAME\vame\model\create_training.py", line 297, in create_trainset traindata_fixed(cfg, files, cfg['test_fraction'], cfg['num_features'], cfg['savgol_filter'], check_parameter) File "D:\anipose\VAME\vame\model\create_training.py", line 239, in traindata_fixed X = np.concatenate(X_train, axis=0).T File "<**array_function** internals>", line 6, in concatenate ValueError: need at least one array to concatenate Creating training dataset... Using robust setting to eliminate outliers! IQR factor: 4 Creating trainset from the vame.csv_to_numpy() output

You can check if you have put the video-1.csv file in pose_estimation folder manually. This step is not showed in workflow but mentioned in essay.

**Comment by Zkkdxbg** [comment]
> Creating training dataset... Using robust setting to eliminate outliers! IQR factor: 4 Creating trainset from the vame.csv_to_numpy() output Traceback (most recent call last): File "c:/Users/kyleb/VAME/vame/initialize_project/demo.py", line 44, in vame.create_trainset(config, check_parameter=False) File "C:\Users\kyleb\AppData\Local\Programs\Python\Python38\lib\site-packages\vame-1.0-py3.8.egg\vame\model\create_training.py", line 297, in create_trainset File "C:\Users\kyleb\AppData\Local\Programs\Python\Python38\lib\site-packages\vame-1.0-py3.8.egg\vame\model\create_training.py", line 239, in traindata_fixed File "<**array_function** internals>", line 180, in concatenate ValueError: need at least one array to concatenate

You can check if you have put the video-1.csv file in pose_estimation folder manually. This step is not showed in workflow but mentioned in essay.

**Comment by xiaoli26** [comment]
I finally solved the problem and I guess it's because I missed some "/" in the “”config = vame.init_new_project()" and even forgot to copy the video at the very beginning(lol). The train model in running now and I hope everything goes well.

Thanks again for the author's reply and your excellent work, and also thanks all the guide from the other users.
